name = "holinic-webflow-translation-simple"
main = "src/worker-simple.js"
compatibility_date = "2024-01-01"

[env.production]
vars = { WEBFLOW_SITE_ID = "62cbaa353a301eb715aa33d0" }

# These will be set as secrets after deployment:
# WEBFLOW_TOKEN - Your Webflow API token
# OPENAI_API_KEY - Your OpenAI API key