name = "webflow-translation-dashboard"
main = "src/translation-worker-complete.js"
compatibility_date = "2024-12-17"
account_id = "7776689e1c22aeed19a74763a55800f2"

# Environment variables
[vars]
WEBFLOW_SITE_ID = "62cbaa353a301eb715aa33d0"

# Force worker to run in US regions only (for OpenAI API access)
# Using Cloudflare's new region hints to ensure US execution
[env.production]
routes = [
  { pattern = "*webflow-translation-dashboard.dndgroup.workers.dev/*", zone_name = "dndgroup.workers.dev" }
]

# Region hints - forces execution in US regions
[env.production.placement]
mode = "smart"
hint = "north-america"

# Durable Objects configuration to pin to US regions
[[durable_objects.bindings]]
name = "REGION_LOCK"
class_name = "RegionLock"
script_name = "webflow-translation-dashboard"

[[migrations]]
tag = "v1"
new_classes = ["RegionLock"]

# Secrets - set these via CLI:
# wrangler secret put WEBFLOW_TOKEN
# wrangler secret put OPENAI_API_KEY