name: Webflow Direct Translation

on:
  workflow_dispatch:
    inputs:
      url_patterns:
        description: 'URL patterns to translate (one per line)'
        required: true
        type: string
        default: 'the-haircare-challenge'
      target_language:
        description: 'Target language code'
        required: true
        default: 'de'
        type: choice
        options:
          - de
          - fr
          - es
          - it
          - pt
          - nl

jobs:
  translate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          cd webflow-translation-system
          npm init -y
          npm install node-fetch@2
      
      - name: Run Direct Translation
        env:
          URL_PATTERNS: ${{ github.event.inputs.url_patterns }}
          TARGET_LANGUAGE: ${{ github.event.inputs.target_language }}
          ACTION: 'translate'
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          WEBFLOW_TOKEN: ${{ secrets.WEBFLOW_TOKEN }}
        run: |
          cd webflow-translation-system
          node scripts/translate-direct.js